---
- hosts: appservers
  become: true
  tasks:
    - name: "Install apache2"
      apt: 
        name:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv
        state: present

