---
- name: deploy vsftpd
  hosts: centos1
  become: false
  tasks:
    - name: install vsftpd
      package:
        name: vsftpd
        state: latest
    - name: enable vsftpd
      service: name=vsftpd enabled=true
    - name: create a readme file
      copy:
        content: "welcome to my friendly server\n"
        dest: /var/README
        force: no
        mode: 0444
