---
- name: Install apache2
  hosts: webservers
  become: true

  vars:
    apache_package: apache2
    web_service: apache2
    rule: http
    system_owner: anna@example.com

  tasks:
  - name: "Install {{ apache_package }}"
    apt:
      name: "{{ apache_package }}"
      state: latest

      #  - name: Insert Index Page
      #    template:
      #      src: index.html
      #      dest: /var/www/html
      #    notify:
      #      - restart {{ web_service }}

  - name: enable mod_rewrite
    apache2_module: name=rewrite state=present
    notify:
      - restart {{ web_service }}

  - name: Enabling proxy module
    apache2_module: name=proxy_http state=present
    notify:
      - restart {{ web_service }}

  - name: deploy website
    git:
      repo: https://github.com/mydadisalive/website.git
      dest: /var/www/html
      accept_hostkey: yes
    notify:
      - restart {{ web_service }}


  - template:
      src: files/http.j2
      dest: /etc/apache2/conf-available
      owner: root
      group: root
      mode: 0644
    notify:
      - restart {{ web_service }}

  handlers:
    - name: enable proxy-config
      shell: a2enconf proxy.conf
      notify:
      - restart {{ web_service }}

    - name: restart {{ web_service }}
      service: name=apache2 state=restarted


- name: verify the webserver is available
  hosts: localhost
  become: false
  tasks:
    - name: test that the webserver is available
      uri:
        url: http://xubuntu1
        status_code: 200
